#created by xiaoya @ tokyo July 12th 2019

from data_cleaning import merge_onehotvector_columns as merge_data

'''
merge_data instance take 3 arguments

attr_min_num : the threshold for image's attribute number, in this case 2 or 1
info_file: info_csv generated by 
merge_column_file:the txt file that provide infomation for duplicated columns


merge_data have merge_column function, it take one file as argument, it will document all the process info in the record_file
'''
merge_instance=merge_data(attr_min_num=1,info_file='info.csv',merge_column_file='duplicated_attributes.txt')
merge_instance.merge_columns()

